export default (
  brand,
  model,
  screenSize,
  color,
  estimatedAmount,
  terms,
  deliveryOption,
  graphicsCard,
  hardDriveCapacity,
  processorType,
  operatingSystem,
  systemMemory,
  qoutation,
) => ({
  brand,
  model,
  screenSize,
  color,
  estimatedAmount,
  terms,
  deliveryOption,
  graphicsCard,
  hardDriveCapacity,
  processorType,
  operatingSystem,
  systemMemory,
  attachments: qoutation,
})
