export default (
  id,
  brand,
  model,
  screenSize,
  color,
  estimatedAmount,
  terms,
  deliveryOption,
  graphicsCard,
  hardDriveCapacity,
  processorType,
  operatingSystem,
  systemMemory,
  qoutation,
  orNumber,
  vendor,
  orDate,
) => ({
  id,
  brand,
  model,
  screenSize,
  color,
  estimatedAmount,
  terms,
  deliveryOption,
  graphicsCard,
  hardDriveCapacity,
  processorType,
  operatingSystem,
  systemMemory,
  attachments: qoutation,
  orNumber,
  vendor,
  orDate,
})
