export default (
  roomNumber,
  houseNumber,
  street,
  subdivision,
  barangay,
  city,
  province,
  zipCode,
  noOfPregnancy,
  expectedDateOfDelivery,
  noOfDelivery,
  noOfMiscarriage,
  ) => ({
    roomNumber,
    houseNumber,
    street,
    subdivision,
    barangay,
    city,
    province,
    zipCode,
    noOfPregnancy,
    expectedDateOfDelivery,
    noOfDelivery,
    noOfMiscarriage,
  })
