export default (
  firstName,
  middleName,
  lastName,
  birthDate,
  occupation,
  contact,
  status,
  gender,
  bloodType,
  healthHospitalizationPlan,
  groupLifeInsurance,
  spouseId,
  spouseAttachmentsArray
) => ({
    firstName,
    middleName,
    lastName,
    birthDate,
    occupation,
    contact,
    status,
    gender,
    bloodType,
    healthHospitalizationPlan,
    groupLifeInsurance,
    spouseId,
    spouseAttachmentsArray
})
