export default (
  parentId,
  firstName,
  lastName,
  middleName,
  genderId,
  relationship,
  statusId,
  contact,
  occupationName,
  birthDate,
  bloodTypeName,
  hospitalization,
  groupPlan) => ({
    parentId,
    firstName,
    lastName,
    middleName,
    genderId,
    relationship,
    statusId,
    contact,
    occupationName,
    birthDate,
    bloodTypeName,
    hospitalization,
    groupPlan,
  })
